/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    
    public static void main(String[] args) {
        
        Car yaris = new Car();

        yaris.setMaxSpeed(100);

        yaris.accelerate(20);
        yaris.accelerate(100);
        
        IO.println("Velocidade atual: " + yaris.getCurrentSpeed());


    }

}
