/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Random;

public class App {

    public static void main(String[] args) {
        Random r = new Random();
        int sorteado = r.nextInt(1, 101);

        String buffer = IO.readln("Digite um número entre 1 e 100: ");
        int numero = Integer.parseInt(buffer);

        int tentativas = 1;

        while (numero != sorteado) {
            if (numero > sorteado) {
                IO.println("O número informado é MAIOR que o sorteado.");
            } else {
                IO.println("O número informado é MENOR que o sorteado.");
            }

            buffer = IO.readln("Tente novamente: ");
            numero = Integer.parseInt(buffer);

            tentativas++;
        }

        IO.println("Parabéns, você acertou!");
        IO.println("Tentativas: " + tentativas);

    }
}
