/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Caneta a = new Caneta(0.06, "Azul");
        // Caneta b = new Caneta(50); // Azul, 50
        // Caneta c = new Caneta(); // Azul, 100

        a.setCor("Verde");

        IO.println(a);

        IO.println(a.desenhar(3, 4, 6, 8));
        IO.println(a.desenhar(3, 4, 6, 8));

    }
}
