/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

import java.util.ArrayList;
import java.util.HashMap;

public class App {

    public static void main(String[] args) {

        ArrayList<String> lista = new ArrayList<>();

        // lista.add("POO");
        // lista.add("ADS");
        // lista.add("IFSC");

        // lista.add(1, "SJE");

        // for i
        for (int i = 0; i < lista.size(); i++) {
            IO.println(lista.get(i));
        }

        // for each
        for (String e : lista) {
            IO.println(e);
        }

        // Método próprio e lambda
        lista.forEach(e -> {
            IO.println(e);
        });

        lista.forEach(e -> IO.println(e));

        // method reference
        lista.forEach(IO::println);

        // remover item
        lista.removeIf(e -> e.equals("ADS"));
        lista.forEach(e -> IO.println(e));

        ArrayList<Pessoa> agenda = new ArrayList<>();

        agenda.add(new Pessoa("Juca", "juca@example.com"));
        agenda.add(new Pessoa("Ana", "ana@example.com"));
        agenda.add(new Pessoa("Pedro", "pedro@example.com"));
        agenda.add(new Pessoa("Juca", "juca@example.org"));

        agenda.removeIf(p -> p.getNome().equals("Juca"));

        // agenda.forEach(IO::println);

        // (chave, valor)
        // chave é o índice para chegar no valor
        // chave é única na coleção

        HashMap<String, String> mapa = new HashMap<>();

        mapa.put("123", "Juca");
        mapa.put("456", "Ana");
        mapa.put("789", "Pedro");

        // Procurar elemento pela chave
        String nome = mapa.get("456");
        IO.println(nome);

        // Imprimir elementos
        mapa.forEach((chave, valor) -> {
            IO.println("chave " + chave + " valor " + valor);
        });

        for (var elemento : mapa.entrySet()) {
            IO.print("chave: " + elemento.getKey());
            IO.println(" valor: " + elemento.getValue());
        }

        // Remover elemento pela chave
        mapa.remove("789");

        // Remover elemento pelo valor
        mapa.values().removeIf(e -> e.equals("Juca"));

    }
}